" --------------------------------------
" GENERATED BY BETTER-VIM    
" Dont touch these files if you want receive better-vim updates.         
" If you need to add new plugins, custom config or override anything
" use the available files on ~/.config/better-vim/ or check the official
" documentation to see more.
" -----------------------------------

source $HOME/.config/nvim/lua/better-vim/plugins.vim
source $HOME/.config/nvim/lua/better-vim/normalize.vim
source $HOME/.config/nvim/lua/better-vim/themes.vim
source $HOME/.config/nvim/lua/better-vim/shortcuts.vim
source $HOME/.config/nvim/lua/better-vim/statusline.vim
source $HOME/.config/nvim/lua/better-vim/tabs.vim
source $HOME/.config/nvim/lua/better-vim/typos.vim
source $HOME/.config/nvim/lua/better-vim/tabs.vim
source $HOME/.config/nvim/lua/better-vim/file-explorer.vim
source $HOME/.config/nvim/lua/better-vim/ui.vim
" Calling the overrides module
source $HOME/.config/better-vim/overrides.vim
